### ISSUE TITLE
Question re broken links

### ISSUE THREAD

**Issue by Sonny-Crockett** [rlach/wiki-import#6]
How do I get it to skip marking the broken links with red stuff? I like the compendium matching, but could we get a setting to just revert to plain text or bold text for a missing link?  Great module, I was trying to do this on my own, so happy this exists. 

![question](https://user-images.githubusercontent.com/39606970/161431999-2896e098-5d37-4146-8c6d-f6070c714a7c.png)

**Comment by rlach** [comment]
Note that in that case you're losing out on future linking. For example if you add "Sullust" few months from now when your players decide to travel there, it would automatically be linked based on name. If we fall back to text it will never be automatched, and you would have to make the link yourself or reimport Onderon (and any places that link to Sullust) to have full linkage power. I'm aware it's not very important for all the users.

If this is just a case of aesthetics you could use custom-css module (https://github.com/cswendrowski/FoundryVTT-Custom-CSS) and add something like this in global css to make it look more pleasant:

```css
.journal-sheet form a.entity-link.content-link.broken {
	box-shadow: none;
	background: inherit;
}

.journal-sheet form a.entity-link.content-link.broken i.fa-unlink {
	display: none;
}
```

Or you could try using https://github.com/farling42/fvtt-disguise-unreachable-links which hides unreachable links to the nonGMs, which probably also works with broken links.

Anyway, this is kind of a workaround you could be using until I have time to implement the solution, but I don't think it would be an ability to skip the links creation during the import process, as I think much better use case would be to run some macro or press another button after you've imported everything to clean up the leftovers. This way you would keep as many links as possible. I will have to think this trough.
